import { reactive } from "vue";
import { useLangConfiguration } from "./langConfiguration";

const { t } = useLangConfiguration();

const list = reactive([
  { name: "Abkhazia", value: "Abkhazia" },
  { name: "Australia", value: "Australia" },
  { name: "Austria", value: "Austria" },
  { name: "Azerbaijan", value: "Azerbaijan" },
  { name: "Aland Islands", value: "Aland Islands" },
  { name: "Albania", value: "Albania" },
  { name: "Algeria", value: "Algeria" },
  { name: "Anguilla", value: "Anguilla" },
  { name: "Angola", value: "Angola" },
  { name: "Andorra", value: "Andorra" },
  { name: "Argentina", value: "Argentina" },
  { name: "Armenia", value: "Armenia" },
  { name: "Aruba", value: "Aruba" },
  { name: "Afghanistan", value: "Afghanistan" },
  { name: "Bahamas", value: "Bahamas" },
  { name: "Bangladesh", value: "Bangladesh" },
  { name: "Barbados", value: "Barbados" },
  { name: "Bahrain", value: "Bahrain" },
  { name: "Belarus", value: "Belarus" },
  { name: "Belize", value: "Belize" },
  { name: "Belgium", value: "Belgium" },
  { name: "Benin", value: "Benin" },
  { name: "Bulgaria", value: "Bulgaria" },
  { name: "Bolivia", value: "Bolivia" },
  { name: "Bosnia & Herzegovina", value: "Bosnia & Herzegovina" },
  { name: "Botswana", value: "Botswana" },
  { name: "Brazil", value: "Brazil" },
  { name: "Brunei Darussalam", value: "Brunei Darussalam" },
  { name: "Burundi", value: "Burundi" },
  { name: "Bhutan", value: "Bhutan" },
  { name: "Vatican City", value: "Vatican City" },
  { name: "United Kingdom", value: "United Kingdom" },
  { name: "Hungary", value: "Hungary" },
  { name: "Venezuela", value: "Venezuela" },
  { name: "Timor, East", value: "Timor, East" },
  { name: "Viet Nam", value: "Viet Nam" },
  { name: "Gabon", value: "Gabon" },
  { name: "Haiti", value: "Haiti" },
  { name: "Gambia", value: "Gambia" },
  { name: "Ghana", value: "Ghana" },
  { name: "Guadeloupe", value: "Guadeloupe" },
  { name: "Guatemala", value: "Guatemala" },
  { name: "Guinea", value: "Guinea" },
  { name: "Guinea-Bissau", value: "Guinea-Bissau" },
  { name: "Germany", value: "Germany" },
  { name: "Gibraltar", value: "Gibraltar" },
  { name: "Hong Kong", value: "Hong Kong" },
  { name: "Honduras", value: "Honduras" },
  { name: "Grenada", value: "Grenada" },
  { name: "Greenland", value: "Greenland" },
  { name: "Greece", value: "Greece" },
  { name: "Georgia", value: "Georgia" },
  { name: "Guam", value: "Guam" },
  { name: "Denmark", value: "Denmark" },
  { name: "Dominica", value: "Dominica" },
  { name: "Dominican Republic", value: "Dominican Republic" },
  { name: "Egypt", value: "Egypt" },
  { name: "Zambia", value: "Zambia" },
  { name: "Western Sahara", value: "Western Sahara" },
  { name: "Zimbabwe", value: "Zimbabwe" },
  { name: "Israel", value: "Israel" },
  { name: "India", value: "India" },
  { name: "Indonesia", value: "Indonesia" },
  { name: "Jordan", value: "Jordan" },
  { name: "Iraq", value: "Iraq" },
  { name: "Iran", value: "Iran" },
  { name: "Ireland", value: "Ireland" },
  { name: "Iceland", value: "Iceland" },
  { name: "Spain", value: "Spain" },
  { name: "Italy", value: "Italy" },
  { name: "Yemen", value: "Yemen" },
  { name: "Kazakhstan", value: "Kazakhstan" },
  { name: "Cambodia", value: "Cambodia" },
  { name: "Cameroon", value: "Cameroon" },
  { name: "Canada", value: "Canada" },
  { name: "Qatar", value: "Qatar" },
  { name: "Kenya", value: "Kenya" },
  { name: "Cyprus", value: "Cyprus" },
  { name: "Kyrgyzstan", value: "Kyrgyzstan" },
  { name: "Kiribati", value: "Kiribati" },
  { name: "China", value: "China" },
  { name: "Colombia", value: "Colombia" },
  { name: "Korea, D.P.R.", value: "Korea, D.P.R." },
  { name: "Korea", value: "Korea" },
  { name: "Costa Rica", value: "Costa Rica" },
  { name: "Cote d'Ivoire", value: "Cote d'Ivoire" },
  { name: "Cuba", value: "Cuba" },
  { name: "Kuwait", value: "Kuwait" },
  { name: "Lao P.D.R.", value: "Lao P.D.R." },
  { name: "Latvia", value: "Latvia" },
  { name: "Lesotho", value: "Lesotho" },
  { name: "Liberia", value: "Liberia" },
  { name: "Lebanon", value: "Lebanon" },
  { name: "Libyan Arab Jamahiriya", value: "Libyan Arab Jamahiriya" },
  { name: "Lithuania", value: "Lithuania" },
  { name: "Liechtenstein", value: "Liechtenstein" },
  { name: "Luxembourg", value: "Luxembourg" },
  { name: "Mauritius", value: "Mauritius" },
  { name: "Mauritania", value: "Mauritania" },
  { name: "Madagascar", value: "Madagascar" },
  { name: "Macedonia", value: "Macedonia" },
  { name: "Malawi", value: "Malawi" },
  { name: "Malaysia", value: "Malaysia" },
  { name: "Mali", value: "Mali" },
  { name: "Maldives", value: "Maldives" },
  { name: "Malta", value: "Malta" },
  { name: "Morocco", value: "Morocco" },
  { name: "Mexico", value: "Mexico" },
  { name: "Mozambique", value: "Mozambique" },
  { name: "Moldova", value: "Moldova" },
  { name: "Monaco", value: "Monaco" },
  { name: "Mongolia", value: "Mongolia" },
  { name: "Namibia", value: "Namibia" },
  { name: "Nepal", value: "Nepal" },
  { name: "Niger", value: "Niger" },
  { name: "Nigeria", value: "Nigeria" },
  { name: "Netherlands", value: "Netherlands" },
  { name: "Nicaragua", value: "Nicaragua" },
  { name: "New Zealand", value: "New Zealand" },
  { name: "Norway", value: "Norway" },
  { name: "United Arab Emirates", value: "United Arab Emirates" },
  { name: "Oman", value: "Oman" },
  { name: "Pakistan", value: "Pakistan" },
  { name: "Panama", value: "Panama" },
  { name: "Paraguay", value: "Paraguay" },
  { name: "Peru", value: "Peru" },
  { name: "Poland", value: "Poland" },
  { name: "Portugal", value: "Portugal" },
  { name: "Russia", value: "Russia" },
  { name: "Romania", value: "Romania" },
  { name: "San Marino", value: "San Marino" },
  { name: "Saudi Arabia", value: "Saudi Arabia" },
  { name: "Senegal", value: "Senegal" },
  { name: "Serbia", value: "Serbia" },
  { name: "Singapore", value: "Singapore" },
  { name: "Syrian Arab Republic", value: "Syrian Arab Republic" },
  { name: "Slovakia", value: "Slovakia" },
  { name: "Slovenia", value: "Slovenia" },
  { name: "Somalia", value: "Somalia" },
  { name: "Sudan", value: "Sudan" },
  { name: "USA", value: "USA" },
  { name: "Tajikistan", value: "Tajikistan" },
  { name: "Thailand", value: "Thailand" },
  { name: "Tanzania", value: "Tanzania" },
  { name: "Togo", value: "Togo" },
  { name: "Tunisia", value: "Tunisia" },
  { name: "Turkmenistan", value: "Turkmenistan" },
  { name: "Turkey", value: "Turkey" },
  { name: "Uganda", value: "Uganda" },
  { name: "Uzbekistan", value: "Uzbekistan" },
  { name: "Ukraine", value: "Ukraine" },
  { name: "Uruguay", value: "Uruguay" },
  { name: "Micronesia", value: "Micronesia" },
  { name: "Fiji", value: "Fiji" },
  { name: "Philippines", value: "Philippines" },
  { name: "Finland", value: "Finland" },
  { name: "France", value: "France" },
  { name: "Croatia", value: "Croatia" },
  { name: "Chad", value: "Chad" },
  { name: "Montenegro", value: "Montenegro" },
  { name: "Czech Republic", value: "Czech Republic" },
  { name: "Chile", value: "Chile" },
  { name: "Switzerland", value: "Switzerland" },
  { name: "Sweden", value: "Sweden" },
  { name: "Sri Lanka", value: "Sri Lanka" },
  { name: "Ecuador", value: "Ecuador" },
  { name: "Eritrea", value: "Eritrea" },
  { name: "Estonia", value: "Estonia" },
  { name: "Ethiopia", value: "Ethiopia" },
  { name: "South Africa", value: "South Africa" },
  { name: "Jamaica", value: "Jamaica" },
  { name: "Japan", value: "Japan" },
]);

const tranlateList = () =>
  list.map((item) => (item.name = t(`countries.${item.name}`)));
tranlateList();

export function useCountries() {
  return { list };
}
