export default {
  state: {
    params: [
      "",
      "Название",
      "Артикул",
      "Себестоимость",
      "Цена",
      "Склад",
      "На складе",
      "Свободно для резерва",
      "В резерве",
      "№ партии",
      "Поступление",
      "НДС",
      "Изменение",
      "Единицы измерений",
      "НДС %",
      "НДС включен в цену",
      "Менеджер может менять % НДС",
      "Описание",
      "Прибыль",
      "Группа",
      "",
    ],
    data: [
      [
        "Товар 1",
        "1",
        "500",
        "509",
        "Склад 1",
        "509",
        "50",
        "51",
        "1",
        "2022-07-13",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Да",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "120",
        "129",
        "Склад 1",
        "129",
        "12",
        "11",
        "2",
        "2022-07-13",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "300",
        "309",
        "Склад 1",
        "309",
        "30",
        "31",
        "2",
        "2022-07-13",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "1500",
        "1509",
        "Склад 1",
        "1509",
        "150",
        "151",
        "3",
        "2022-07-13",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Да",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 2",
        "2",
        "1800",
        "1809",
        "Склад 1",
        "1809",
        "180",
        "181",
        "1",
        "2022-07-14",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 3",
        "3",
        "13",
        "19",
        "Склад 1",
        "19",
        "1",
        "1",
        "2",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 4",
        "4",
        "117",
        "119",
        "Склад 1",
        "119",
        "11",
        "11",
        "3",
        "2022-07-13",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 5",
        "5",
        "4356",
        "4359",
        "Склад 2",
        "4359",
        "435",
        "431",
        "2",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Да",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 6",
        "6",
        "67589",
        "67589",
        "Склад 2",
        "67589",
        "6758",
        "6751",
        "2",
        "2022-07-11",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 7",
        "7",
        "123",
        "129",
        "Склад 2",
        "129",
        "12",
        "11",
        "1",
        "2022-07-11",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 8",
        "8",
        "123",
        "129",
        "Склад 2",
        "129",
        "12",
        "11",
        "1",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 9",
        "9",
        "123",
        "129",
        "Склад 2",
        "129",
        "12",
        "11",
        "2",
        "2022-07-11",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 9",
        "9",
        "123",
        "129",
        "Склад 2",
        "129",
        "12",
        "11",
        "3",
        "2022-07-28",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Да",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 10",
        "10",
        "123",
        "129",
        "Склад 2",
        "129",
        "12",
        "11",
        "3",
        "2022-07-16",
        "Да",
        "2022-07-18T11:21",
        "шт",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
    ],
    service: [
      [
        "Услуга 1",
        "1",
        "1500",
        "1509",
        "",
        "",
        "",
        "",
        "",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Услуга 2",
        "2",
        "1800",
        "1809",
        "",
        "",
        "",
        "",
        "",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Услуга 3",
        "3",
        "13",
        "19",
        "",
        "",
        "",
        "",
        "",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 1",
      ],
      [
        "Услуга 1",
        "1",
        "1500",
        "1509",
        "",
        "",
        "",
        "",
        "",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "",
        "3",
        "Нет",
        "Да",
        "1234",
        "Да",
        "Группа 2",
      ],
      [
        "Услуга 1",
        "1",
        "1500",
        "1509",
        "",
        "",
        "",
        "",
        "",
        "2022-07-18",
        "Да",
        "2022-07-18T11:21",
        "",
        "3",
        "Нет",
        "Да",
        "123",
        "Да",
        "Группа 2",
      ],
    ],
    sync_list_stuff_options: [
      { name: "Не выбрано", value: 1 },
      { name: "Товары", value: 2 },
    ],
    sync_list_hide_tab_options: [
      { name: "Не выбрано", value: 1 },
      { name: "Основное", value: 2 },
      { name: "Сделки", value: 3 },
      { name: "Docs", value: 4 },
      { name: "Склад", value: 5 },
      { name: "Товары", value: 6 },
      { name: "Документы", value: 7 },
      { name: "Статистика", value: 8 },
      { name: "Счета/покупки", value: 9 },
      { name: "Корреспонденция", value: 10 },
      { name: "Анкета", value: 11 },
      { name: "Авто", value: 12 },
      { name: "Финансы", value: 13 },
      { name: "Документы", value: 14 },
      { name: "Чек-лист", value: 15 },
      { name: "DocsSls", value: 16 },
      { name: "Реквизиты", value: 17 },
    ],
    sync_list_stuff_selected_option: { name: "Не выбрано", value: 1 },
    sync_list_hide_tab_selected_option: { name: "Не выбрано", value: 1 },
    types: [
      { name: "Число целое", value: 1 },
      { name: "Дробное число", value: 2 },
      { name: "Строка", value: 3 },
      { name: "Текст", value: 4 },
      { name: "Список", value: 5 },
      { name: "Мильтисписок", value: 6 },
      { name: "Дата", value: 7 },
      { name: "Дата-Время", value: 8 },
      { name: "Флаг", value: 9 },
    ],
    fields: [
      {
        id: 1,
        field: "Название",
        type: { name: "Строка", value: 3 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 2,
        field: "Артикул",
        type: { name: "Строка", value: 3 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 3,
        field: "Себестоимость",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 4,
        field: "Цена",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 5,
        field: "Склад",
        type: { name: "Список", value: 5 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Склад 1", value: 2 },
          { name: "Склад 2", value: 3 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: false,
      },
      {
        id: 6,
        field: "На складе",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: false,
      },
      {
        id: 7,
        field: "Свободно для резерва",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: false,
        visibility: true,
        edit: false,
        editing: false,
        delete: true,
        available_to_services: false,
      },
      {
        id: 8,
        field: "В резерве",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: false,
      },
      {
        id: 9,
        field: "№ партии",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: false,
      },
      {
        id: 10,
        field: "Поступление",
        type: { name: "Дата", value: 7 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 11,
        field: "НДС",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 12,
        field: "Изменение",
        type: { name: "Дата-Время", value: 8 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 13,
        field: "Единицы измерений",
        type: { name: "Список", value: 5 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "шт", value: 2 },
          { name: "л (литры)", value: 3 },
          { name: "м3 (кубические метры)", value: 4 },
          { name: "кг (килограммы)", value: 5 },
          { name: "т (тонны)", value: 6 },
          { name: "комплект", value: 7 },
          { name: "услуга", value: 8 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: false,
      },
      {
        id: 14,
        field: "НДС %",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 15,
        field: "НДС включен в цену",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 16,
        field: "Менеджер может менять % НДС",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 17,
        field: "Описание",
        type: { name: "Текст", value: 4 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
      {
        id: 18,
        field: "Прибыль",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: false,
        visibility: false,
        edit: false,
        editing: false,
        delete: true,
        available_to_services: true,
      },
      {
        id: 19,
        field: "Группа",
        type: { name: "Мильтисписок", value: 6 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Группа 1", value: 2 },
          { name: "Группа 2", value: 3 },
          { name: "Группа 3", value: 4 },
          { name: "Группа 4", value: 5 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
        available_to_services: true,
      },
    ],
    items_from_storage: [
      {
        id: 1,
        name: "Тест калькулятора",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Не складывать", value: 2 },
          { name: "Сложить", value: 3 },
          { name: "Умножить", value: 4 },
          { name: "Вычесть", value: 5 },
          { name: "Поделить", value: 6 },
        ],
        reserve_disable_change: false,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Не складывать", value: 2 },
          { name: "Сложить", value: 3 },
          { name: "Умножить", value: 4 },
          { name: "Вычесть", value: 5 },
          { name: "Поделить", value: 6 },
        ],
        cancellation_disable_change: true,
      },
      {
        id: 2,
        name: "Рассмотрение заемщика",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: false,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 3,
        name: "Заемщик одобрен",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: false,
      },
      {
        id: 4,
        name: "Объект залога одобрен",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 5,
        name: "Процесс сделки",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 6,
        name: "Test",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 7,
        name: "ТЕСТ УНИВЕР",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 8,
        name: "Nethouse TEST",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 9,
        name: "тест Чек-лист",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 10,
        name: "Сопряжение",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 11,
        name: "Тест товаров",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 12,
        name: "Тест генерации документов",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 13,
        name: "Праздники",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 14,
        name: "Тест сенсей",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 15,
        name: "Тест Реквизиты",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
    ],
    binding_fields_deals: [
      {
        id: 1,
        name: "Товары",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: false,
      },
      {
        id: 2,
        name: "Себестоимость",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 3,
        name: "Прибыль",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 4,
        name: "Общий бюджет",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 5,
        name: "НДС сумма",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
    ],
    catalog: [
      {
        name: "Остатки",
        value: "home",
      },
      {
        name: "Аналитика",
        value: "analytics",
      },
      {
        name: "Архив",
        value: "archive",
      },
      {
        name: "Инструкции",
        value: "instructions",
      },
    ],
    archive: {
      titles: [
        "Название",
        "Артикул",
        "№ партии",
        "На складе",
        "Цена",
        "Себестоимость",
        "Описание",
      ],
      sourses: [0],
      items: [
        [
          "Товар 9",
          "9",
          "4",
          "3",
          "Склад 2",
          "2",
          "12",
          "11",
          "1",
          "2022-07-11",
          "Да",
          "2022-07-18T11:21",
          "шт",
          "3",
          "Нет",
          "Да",
          "5",
          "Да",
          "Группа 2",
        ],
      ],
    },
    documents: [
      {
        name: "Счет",
        serviceID: "13U76ujSjV_iaY0L2WBVHVw7q07TSEqstuL0kSeX-Sh8",
        gauge: "редактировать",
        gouge_type: "xlsx",
        download_type: "pdf",
      },
      {
        name: "Тест",
        serviceID: "1SXnFH7iILXuduumj8PNhi8w1xQfchHKK	",
        gauge: "редактировать",
        gouge_type: "xlsx",
        download_type: "Исходный",
      },
    ],
    show_columns: {
      names: ["Все остатки", "Склад 1", "Склад 2", "Услуги"],
      values: [
        [
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
          true,
        ],
        [
          true,
          true,
          false,
          true,
          false,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          true,
          true,
          false,
          true,
          false,
          true,
          true,
          true,
          true,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
        [
          true,
          true,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          true,
          false,
          true,
          true,
          true,
          true,
          true,
          true,
        ],
      ],
    },
  },
  getters: {
    data(state) {
      return state.data;
    },
    get_data_storage(state) {
      const storage_idx = state.params.indexOf("Склад") - 1;
      const result = {};
      let storages = [];
      let fields_stor_idx = null;
      state.fields.forEach((val) => {
        if (val.field == "Склад") {
          fields_stor_idx = val.id - 1;
        }
      });
      state.fields[fields_stor_idx].selector_options.forEach((val) => {
        storages.push(val.name);
      });
      storages.shift();
      storages.forEach((val) => {
        result[val] = [];
      });
      storages.forEach((val) => {
        state.data.forEach((value) => {
          if (value[storage_idx] == val) result[val].push(value);
        });
      });
      return result;
    },
    service(state) {
      return state.service;
    },
    params(state) {
      return state.params;
    },
    types(state) {
      return state.types;
    },
    fields(state) {
      return state.fields;
    },
    sync_list_stuff_options(state) {
      return state.sync_list_stuff_options;
    },
    sync_list_hide_tab_options(state) {
      return state.sync_list_hide_tab_options;
    },
    sync_list_stuff_selected_option(state) {
      return state.sync_list_stuff_selected_option;
    },
    sync_list_hide_tab_selected_option(state) {
      return state.sync_list_hide_tab_selected_option;
    },
    items_from_storage(state) {
      return state.items_from_storage;
    },
    binding_fields_deals(state) {
      return state.binding_fields_deals;
    },
    catalog(state) {
      return state.catalog;
    },
    archive(state) {
      return state.archive;
    },
    coun_archive(state) {
      return state.archive.items.length;
    },
    options_from_name: (state) => {
      const result = {};
      state.fields.forEach((val) => {
        result[val.field] = val.selector_options;
      });
      return result;
    },
    documents(state) {
      return state.documents;
    },
    show_columns(state) {
      const result = {};
      state.show_columns.names.forEach((val, idx) => {
        result[val] = state.show_columns.values[idx];
      });
      return result;
    },
  },
  mutations: {
    update_data(state, data) {
      state.data = data;
    },
    update_data_idx(state, payload) {
      state.data[payload.idx] = payload.data;
    },
    update_all_data(state, new_field) {
      state.data.forEach((val, idx) => {
        state.data[idx].push(new_field);
      });
    },
    add_new_data(state, payload) {
      let dat = [];
      state.params.forEach(() => dat.push(""));
      dat.pop();
      dat.pop();
      payload.title.forEach((val, idx) => {
        const data_idx = state.params.indexOf(val) - 1;
        if (data_idx >= 0) dat[data_idx] = payload.new_data[idx];
      });
      state.data.push(dat);
    },
    cancel_item_in_data(state, payload) {
      const count_idx = state.params.indexOf(payload.name) - 1;
      const old_val = state.data[payload.idx][count_idx];
      state.data[payload.idx][count_idx] = old_val - payload.count;
    },
    delete_data_idx(state, idxes) {
      state.data.forEach((val, index) => {
        idxes.forEach((value) => {
          state.data[index].splice(value, 1);
        });
      });
    },
    remove_data_idx(state, payload) {
      state.data.splice(payload.idx, 1);
    },
    add_data(state, payload) {
      state.data.push(payload.data);
    },
    archive_data(state, idxes) {
      idxes.forEach((idx) => state.archive.items.push(state.data[idx]));
      state.archive.sourses.push(0);
      const idxes_reverse = idxes.reverse();
      idxes_reverse.forEach((idx) => state.data.splice(idx, 1));
    },
    unarchive_data(state, idx) {
      state.data.push(state.archive.items[idx]);
      state.archive.sourses.splice(idx, 1);
      state.archive.items.splice(idx, 1);
    },
    archive_service(state, idxes) {
      idxes.forEach((idx) => state.archive.items.push(state.service[idx]));
      state.archive.sourses.push(1);
      const idxes_reverse = idxes.reverse();
      idxes_reverse.forEach((idx) => state.service.splice(idx, 1));
    },
    unarchive_service(state, idx) {
      state.service.push(state.archive.items[idx]);
      state.archive.sourses.splice(idx, 1);
      state.archive.items.splice(idx, 1);
    },
    add_new_service(state, payload) {
      let dat = [];
      state.params.forEach(() => dat.push(""));
      dat.pop();
      dat.pop();
      payload.title.forEach((val, idx) => {
        const data_idx = state.params.indexOf(val) - 1;
        if (data_idx >= 0) dat[data_idx] = payload.new_data[idx];
      });
      state.service.push(dat);
    },
    update_service_idx(state, payload) {
      state.service[payload.idx] = payload.data;
    },
    remove_service_idx(state, payload) {
      state.service.splice(payload.idx, 1);
    },
    add_service(state, payload) {
      state.service.push(payload.data);
    },
    update_columns(state, payload) {
      const idx = state.show_columns.names.indexOf(payload.name);
      state.show_columns.values[idx] = [];
      state.show_columns.values[idx] = state.show_columns.values[idx].concat(
        payload.value
      );
    },
    update_params(state, params) {
      state.params = params;
    },
    update_fields(state, fields) {
      state.fields = fields;
    },
    update_sync_list_stuff_selected_option(state, option) {
      Object.assign(state.sync_list_stuff_selected_option, option);
    },
    update_sync_list_hide_tab_selected_option(state, option) {
      Object.assign(state.sync_list_hide_tab_selected_option, option);
    },
    update_items_from_storage(state, items_from_storage) {
      state.items_from_storage = items_from_storage;
    },
    update_binding_fields_deals(state, binding_fields_deals) {
      state.binding_fields_deals = binding_fields_deals;
    },
    save_new_doc(state, new_doc) {
      state.documents.push(Object.assign(new_doc, { gauge: "редактировать" }));
    },
    save_cur_doc(state, payload) {
      Object.assign(state.documents[payload.idx], payload.cur_doc);
    },
    delete_cur_doc(state, idx) {
      state.documents.splice(idx, 1);
    },
  },
  actions: {},
};
