export default {
  state: {
    params: [
      "",
      "Название",
      "Артикул",
      "Себестоимость",
      "Цена",
      "Склад",
      "На складе",
      "Свободно для резерва",
      "В резерве",
      "№ партии",
      "Поступление",
      "НДС",
      "Изменение",
      "Единицы измерений",
      "НДС %",
      "НДС включен в цену",
      "Менеджер может менять % НДС",
      "Описание",
      "Прибыль",
      "Группа",
      "",
    ],
    data: [
      [
        "Товар 1",
        "1",
        "500",
        "Bret",
        "Склад 1",
        "Leanne Graham",
        "1-770-736-8031 x56442",
        "Склад 1",
        "1",
        "2022-07-08",
        "Да",
        "2022-07-08T21:21",
        "шт",
        "3",
        "Да",
        "Нет",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "120",
        "Bret",
        "Склад 1",
        "Leanne Graham",
        "1-770-736-8031 x56442",
        "Склад 1",
        "шт",
        "2Leanne Graham",
        "Да",
        "3",
        "шт",
        "3",
        "Да",
        "Нет",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "300",
        "Bret",
        "Склад 1",
        "Ervin Howell",
        "010-692-6593 x09125",
        "Склад 1",
        "",
        "Ervin Howell",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 1",
        "1",
        "1500",
        "Bret",
        "Склад 1",
        "Clementine Bauch",
        "1-463-123-4447",
        "Склад 1",
        "",
        "Clementine Bauch",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 2",
        "2",
        "180000",
        "Antonette",
        "Склад 1",
        "Ervin Howell",
        "010-692-6593 x09125",
        "Склад 2",
        "шт",
        "Ervin Howell",
        "Да",
        "3",
        "шт",
        "3",
        "Да",
        "Нет",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 3",
        "3",
        "13",
        "Samantha",
        "Склад 1",
        "Clementine Bauch",
        "1-463-123-4447",
        "Склад 1",
        "",
        "Clementine Bauch",
        "Да",
        "3",
        "шт",
        "3",
        "Да",
        "Нет",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 4",
        "4",
        "117",
        "Karianne",
        "Склад 2",
        "Patricia Lebsack",
        "493-170-9623 x156",
        "Склад 1",
        "",
        "Patricia Lebsack",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 1",
      ],
      [
        "Товар 5",
        "5",
        "4356",
        "Kamren",
        "Склад 2",
        "Chelsey Dietrich",
        "(254)954-1289",
        "Склад 2",
        "",
        "Chelsey Dietrich",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 6",
        "6",
        "67589",
        "Leopoldo_Corkery",
        "Склад 2",
        "Mrs. Dennis Schulist",
        "1-477-935-8478 x6430",
        "Склад 2",
        "",
        "Mrs. Dennis Schulist",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 7",
        "7",
        "123",
        "Elwyn.Skiles",
        "Склад 2",
        "Kurtis Weissnat",
        "210.067.6132",
        "Склад 2",
        "",
        "Kurtis Weissnat",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 8",
        "8",
        "123",
        "Maxime_Nienow",
        "Склад 2",
        "Nicholas Runolfsdottir V",
        "586.493.6943 x140",
        "Склад 2",
        "",
        "Nicholas Runolfsdottir V",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 9",
        "9",
        "123",
        "Delphine",
        "Склад 2",
        "Glenna Reichert",
        "(775)976-6794 x41206",
        "Склад 2",
        "",
        "Glenna Reichert",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 9",
        "9",
        "123",
        "Delphine",
        "Склад 2",
        "Glenna Reichert",
        "(775)976-6794 x41206",
        "Склад 2",
        "",
        "Glenna Reichert",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
      [
        "Товар 10",
        "10",
        "123",
        "Moriah.Stanton",
        "Склад 2",
        "Clementina DuBuque",
        "024-648-3804",
        "Склад 12",
        "",
        "Clementina DuBuque",
        "",
        "3",
        "шт",
        "3",
        "3",
        "3",
        "1",
        "Да",
        "Группа 2",
      ],
    ],
    sync_list_stuff_options: [
      { name: "Не выбрано", value: 1 },
      { name: "Товары", value: 2 },
    ],
    sync_list_hide_tab_options: [
      { name: "Не выбрано", value: 1 },
      { name: "Основное", value: 2 },
      { name: "Сделки", value: 3 },
      { name: "Docs", value: 4 },
      { name: "Склад", value: 5 },
      { name: "Товары", value: 6 },
      { name: "Документы", value: 7 },
      { name: "Статистика", value: 8 },
      { name: "Счета/покупки", value: 9 },
      { name: "Корреспонденция", value: 10 },
      { name: "Анкета", value: 11 },
      { name: "Авто", value: 12 },
      { name: "Финансы", value: 13 },
      { name: "Документы", value: 14 },
      { name: "Чек-лист", value: 15 },
      { name: "DocsSls", value: 16 },
      { name: "Реквизиты", value: 17 },
    ],
    sync_list_stuff_selected_option: { name: "Не выбрано", value: 1 },
    sync_list_hide_tab_selected_option: { name: "Не выбрано", value: 1 },
    types: [
      { name: "Число целое", value: 1 },
      { name: "Дробное число", value: 2 },
      { name: "Строка", value: 3 },
      { name: "Текст", value: 4 },
      { name: "Список", value: 5 },
      { name: "Мильтисписок", value: 6 },
      { name: "Дата", value: 7 },
      { name: "Дата-Время", value: 8 },
      { name: "Флаг", value: 9 },
    ],
    fields: [
      {
        id: 1,
        field: "Название",
        type: { name: "Строка", value: 3 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 2,
        field: "Артикул",
        type: { name: "Строка", value: 3 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 3,
        field: "Себестоимость",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 4,
        field: "Цена",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 5,
        field: "Склад",
        type: { name: "Список", value: 5 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Склад 1", value: 2 },
          { name: "Склад 2", value: 3 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 6,
        field: "На складе",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 7,
        field: "Свободно для резерва",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: false,
        visibility: true,
        edit: false,
        editing: false,
        delete: true,
      },
      {
        id: 8,
        field: "В резерве",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 9,
        field: "№ партии",
        type: { name: "Число целое", value: 1 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 10,
        field: "Поступление",
        type: { name: "Дата", value: 7 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 11,
        field: "НДС",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 12,
        field: "Изменение",
        type: { name: "Дата-Время", value: 8 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 13,
        field: "Единицы измерений",
        type: { name: "Список", value: 5 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "шт", value: 2 },
          { name: "л (литры)", value: 3 },
          { name: "м3 (кубические метры)", value: 4 },
          { name: "кг (килограммы)", value: 5 },
          { name: "т (тонны)", value: 6 },
          { name: "комплект", value: 7 },
          { name: "услуга", value: 8 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 14,
        field: "НДС %",
        type: { name: "Дробное число", value: 2 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 15,
        field: "НДС включен в цену",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 16,
        field: "Менеджер может менять % НДС",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 17,
        field: "Описание",
        type: { name: "Строка", value: 3 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
      {
        id: 18,
        field: "Прибыль",
        type: { name: "Флаг", value: 9 },
        selector_options: [{ name: "", value: 1 }],
        disable_change_type: false,
        visibility: false,
        edit: false,
        editing: false,
        delete: true,
      },
      {
        id: 19,
        field: "Группа",
        type: { name: "Мильтисписок", value: 6 },
        selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Группа 1", value: 2 },
          { name: "Группа 2", value: 3 },
          { name: "Группа 3", value: 4 },
          { name: "Группа 4", value: 5 },
        ],
        disable_change_type: true,
        visibility: true,
        edit: false,
        editing: false,
        delete: false,
      },
    ],
    items_from_storage: [
      {
        id: 1,
        name: "Тест калькулятора",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Не складывать", value: 2 },
          { name: "Сложить", value: 3 },
          { name: "Умножить", value: 4 },
          { name: "Вычесть", value: 5 },
          { name: "Поделить", value: 6 },
        ],
        reserve_disable_change: false,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [
          { name: "Не выбрано", value: 1 },
          { name: "Не складывать", value: 2 },
          { name: "Сложить", value: 3 },
          { name: "Умножить", value: 4 },
          { name: "Вычесть", value: 5 },
          { name: "Поделить", value: 6 },
        ],
        cancellation_disable_change: true,
      },
      {
        id: 2,
        name: "Рассмотрение заемщика",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: false,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 3,
        name: "Заемщик одобрен",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: false,
      },
      {
        id: 4,
        name: "Объект залога одобрен",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 5,
        name: "Процесс сделки",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 6,
        name: "Test",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 7,
        name: "ТЕСТ УНИВЕР",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 8,
        name: "Nethouse TEST",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 9,
        name: "тест Чек-лист",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 10,
        name: "Сопряжение",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 11,
        name: "Тест товаров",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 12,
        name: "Тест генерации документов",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 13,
        name: "Праздники",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 14,
        name: "Тест сенсей",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
      {
        id: 15,
        name: "Тест Реквизиты",
        reserve_selected_option: { name: "Не выбрано", value: 1 },
        reserve_selector_options: [{ name: "Не выбрано", value: 1 }],
        reserve_disable_change: true,
        cancellation_selected_option: { name: "Не выбрано", value: 1 },
        cancellation_selector_options: [{ name: "Не выбрано", value: 1 }],
        cancellation_disable_change: true,
      },
    ],
    binding_fields_deals: [
      {
        id: 1,
        name: "Товары",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: false,
      },
      {
        id: 2,
        name: "Себестоимость",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 3,
        name: "Прибыль",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 4,
        name: "Общий бюджет",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
      {
        id: 5,
        name: "НДС сумма",
        binding_selected_option: { name: "Не выбрано", value: 1 },
        binding_selector_options: [{ name: "Не выбрано", value: 1 }],
        binding_disable_change: true,
      },
    ],
  },
  getters: {
    data(state) {
      return state.data;
    },
    params(state) {
      return state.params;
    },
    types(state) {
      return state.types;
    },
    fields(state) {
      return state.fields;
    },
    sync_list_stuff_options(state) {
      return state.sync_list_stuff_options;
    },
    sync_list_hide_tab_options(state) {
      return state.sync_list_hide_tab_options;
    },
    sync_list_stuff_selected_option(state) {
      return state.sync_list_stuff_selected_option;
    },
    sync_list_hide_tab_selected_option(state) {
      return state.sync_list_hide_tab_selected_option;
    },
    items_from_storage(state) {
      return state.items_from_storage;
    },
    binding_fields_deals(state) {
      return state.binding_fields_deals;
    },
  },
  mutations: {
    update_data(state, data) {
      state.data = data;
    },
    update_data_idx(state, payload) {
      state.data[payload.idx] = payload.data;
    },
    update_all_data(state, new_field) {
      state.data.forEach((val, idx) => {
        state.data[idx].push(new_field);
      });
    },
    add_new_data(state, payload) {
      let dat = [];
      state.data[0].forEach(() => dat.push(""));
      dat[1] = payload[0];
      dat[0] = payload[1];
      dat[8] = payload[3];
      dat[2] = payload[6];
      dat[3] = payload[7];
      dat[10] = payload[8];
      dat[14] = payload[9];
      dat[15] = payload[10];
      dat[13] = payload[11];
      state.data.push(dat);
    },
    delete_data_idx(state, idxes) {
      state.data.forEach((val, index) => {
        idxes.forEach((value) => {
          state.data[index].splice(value, 1);
        });
      });
    },
    update_params(state, params) {
      state.params = params;
    },
    update_fields(state, fields) {
      state.fields = fields;
    },
    update_sync_list_stuff_selected_option(state, option) {
      Object.assign(state.sync_list_stuff_selected_option, option);
    },
    update_sync_list_hide_tab_selected_option(state, option) {
      Object.assign(state.sync_list_hide_tab_selected_option, option);
    },
    update_items_from_storage(state, items_from_storage) {
      state.items_from_storage = items_from_storage;
    },
    update_binding_fields_deals(state, binding_fields_deals) {
      state.binding_fields_deals = binding_fields_deals;
    },
  },
  actions: {},
};
